### ISSUE TITLE
ElementViewAdapter Fault Tolerance

### ISSUE THREAD

**Issue by advation** [Staple-Code/Staple-Code#22]
This only effects the Forms Refactoring branch.

Allow the parameter "elementViewAdapter" under forms in application.ini to be set to nothing if a form view adapter is not required.

**Comment by hansheeling** [comment]
Issue is corrected. Error was due to type casting in FieldElementClass, if not form adapter was loaded in form.class.php, then a null was passed to FieldElement.class.php thus erroring. Updated form.class.php to check if property is set before trying to pass it.
