### ISSUE TITLE
Form Element Instructions not displaying in echoed out form. 

### ISSUE THREAD

**Issue by advation** [Staple-Code/Staple-Code#24]
This only effects the FormsRefactor branch.
The $field->getInstructions() doesn't seem to be pulling across when an element is echoed out.

**Comment by hansheeling** [comment]
Corrected the issue with Instructions not echoing when foundationViewAdapter in use. Error was check if instructions existed in the view adapter. Instructions now echo as expected. 

Also added addInstructions method to alias setInstructions method to maintain consistency in terminology adding properties to and element.
