### ISSUE TITLE
Short Form Creation

### ISSUE THREAD

**Issue by ironpilot** [Staple-Code/Staple-Code#28]
I propose an addition to the form objects that will make creating form fields quicker and easier for everyone using this system. This is similar to the way that I've made the Query objects work.

What I propose is to encapsulate Form, FieldElement, Filter and Validator object creation into the Form object itself so that the developer could make calls similar to this:

```
$form = Form::create('MyForm','/form/submit'); //Create a new form with the name MyForm and the Action /form/submit
$form->textElement('FirstName','Enter Your First Name') //new field with the name "FirstName" and the label "Enter Your First Name", returns the field object for further modification
     ->setRequired()     //call the setRequired method
     ->addFilter(Filter::tags())     //Add a tag filter to the field
     ->addValidator(Validate::length(1,2));     //Add a new validator to the field to ensure field length

$form->FirstName->setValue('Nick');     //Field accessed dynamically on the form object and the setValue method called.
```

This would make the form creation system a little more short-handed, even than what we did with the renaming system previously. Also this removes the need for extra `use` statements to make code completion work at the top of each file because each element object is not directly referenced in the developer's code.

What do you guys think? Is there an even better way that we could do this?

**Comment by advation** [comment]
I think that's a great idea! I really don't have any further suggestions about how else to go about it. My only question would be, would this new format still keep backwards compatibility?

**Comment by ironpilot** [comment]
This is an addition to the Form object. Nothing would be removed. So maintaining backward compatibility wouldn't really even be an issue here I don't think. You would still be able to write the above as:

```
$form = new Form();
$form->setName('MyForm')
     ->setAction('/form/submit');
$text = new TextElement('FirstName','Enter Your First Name');
$text->setRequired()     //call the setRequired method
     ->addFilter(new TagsFilter())     //Add a tag filter to the field
     ->addValidator(new LengthValidator(1,2));     //Add a new validator to the field to ensure field length

$form->addField($text);

$form->fields['FirstName']->setValue('Nick'); 
```

Obviously the former has the advantage of being much more succinct. This is the advantage of object encapsulation. :)

**Comment by ironpilot** [comment]
Fixed in https://github.com/ironpilot/Staple-Code/pull/45
