### ISSUE TITLE
Staple_Form_CheckboxGroup() returns empty array

### ISSUE THREAD

**Issue by ericnutsch** [Staple-Code/Staple-Code#41]
Staple_Form_CheckboxGroup()  and Staple_Form_FoundationCheckboxGroup()  return an empty array.

What it is returning:
Array ( [ident] => fc1003b8105210d99d17f1fb97eb52476b6 [32] => [31] => [55] => [29] => [30] => [33] => [submit] => Save [quote_id] => 11210 )

It should be returning:
Array ( [ident] => fc1003b8105210d99d17f1fb97eb52476b6 [32] => [31] => [55] => [29] => 1 [30] => [33] => [submit] => Save [quote_id] => 11210 )

I dont know anything but;
If i have to build an array of checkbox elements to feed it, there is no point in this method.

```
    foreach($this->optionsArray as $key => $value){
    $checkbox= new Staple_Form_FoundationCheckboxElement($key,$value);
    $this->addField($checkbox);
    };
```

vs

```
    foreach($this->optionsArray as $key => $value){
    $checkboxobjarray[]= new Staple_Form_FoundationCheckboxElement($key,$value);
    };
    $test = new Staple_Form_FoundationCheckboxGroup('feature_rev_id_array',$this->categoryname);
    $test->addCheckboxArray($checkboxobjarray);
        $this->addField( $test);
```

**Comment by ironpilot** [comment]
The functionality has been corrected in a previous change. This now works by returning booleans for each checkbox in the group element. Example:
```
Array (
    'Checkbox1' => false
    'Checkbox2' => true
    'Checkbox3' => false
)
```
