### ISSUE TITLE
Add Twig Support and/or Create a Templating Engine

### ISSUE THREAD

**Issue by ironpilot** [Staple-Code/Staple-Code#43]
Twig is a PHP templating engine that I think we should consider adding support for. It can be included via composer into a project. Then all we would have to do is to add a method for our layout and view objects to utilize twig when rendering content.

http://twig.sensiolabs.org/
http://twig.sensiolabs.org/doc/api.html

The other option would be to create our own simplistic template engine. Which might also have some advantages. I do like Twig's double curly brace syntax `{{ variable|escape }}` and the way that filters can be added to it.

Thoughts?

**Comment by advation** [comment]
I think this would be an excellent addition!

**Comment by ironpilot** [comment]
Fixed by #56.
This will integrate Twig with Staple.
