### ISSUE TITLE
Action parameters in the URI dont support underscores

### ISSUE THREAD

**Issue by ericnutsch** [Staple-Code/Staple-Code#48]
If you add an underscore to a GET variable, like this:
http://llcom/settings/mssqltableview/OPERATION_SCHED

It attempts to route to it instead of pass it as a variable.

My workaround is a string replace with a dash on both ends
str_replace("_","-", $row["Table_name"])
str_replace("-","_", $this->tablename)

**Comment by scotthenscheid** [comment]
That is not a GET variable. A GET variable is going to occur after the ? character in the URL string. These are parameters in the controller action. We could change some things around to specifically support underscores in action parameters. There is logic in the code currently to filter this data to be only alpha-numeric with dashes. So this is working as designed.

Perhaps you should actually use this as a GET parameter and then you would not be subject to the current restriction. That would change your URL to: http://llcom/settings/mssqltableview?OPERATION_SCHED
