### ISSUE TITLE
session_regenerate_id() in PHP 7

### ISSUE THREAD

**Issue by hansheeling** [Staple-Code/Staple-Code#60]
Catchable fatal error: session_regenerate_id(): Failed to create(read) session ID: user (path: C:\Windows\temp) in C:\Users\Hans\Projects\websites\LibraryApp\website\library\Staple\Session\Session.class.php on line 286

Error occurs when running PHP 7

Issue looks to be due to PHP 7 requiring a string to be returned where PHP 5 was fine with getting boolean false. 

Tested same project with PHP 5.6 and no issue.

**Comment by ironpilot** [comment]
fixed with https://github.com/ironpilot/Staple-Code/pull/62
