### ISSUE TITLE
Fix Documentation Accordion and Ordering

### ISSUE THREAD

**Issue by scotthenscheid** [Staple-Code/Staple-Code#90]
The accordion on the documentation site does not collapse and the sorting of the list needs to be adjusted to have "Introduction" at the top of the list.

![image](https://cloud.githubusercontent.com/assets/10855826/24001889/e134b04a-0a24-11e7-8b39-3c531980dc50.png)

**Comment by ironpilot** [comment]
Preferably if the documentation sections could be ordered manually, that would be the most useful.

**Comment by ironpilot** [comment]
I was able to fix this issue by removing the sort on the categories. Now the category order is defined by the document dates.
